# safelist
branches:
  only:
    - develop
    - master

# Python versions to test
language: python
  - "3.7"

# install dependencies
install:
  - pip install -r requirements38.txt

script:
  - pytest
