language: python
jobs:
  include:
    - name "Python 3.7.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.5
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
branches:
  only:
    - develop
    - master

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script:
  - pytest
