language: python            # this works for Linux but is an error on macOS or Windows

git:
  depth: 3                  # This will clone the repo to depth specified. Useful only when performing git operation. Max is 50.

branches:
  only:                     # branch safelist
    - master
    - develop
  except:                   # branch blocklist. If both safelist and blocklist included, safelist takes precedence.
    - legacy
    - experimental

jobs:
  include:
    # Windows Tests for Python 3:
    # Currently available versions are 3.5.4, 3.6.8, 3.7.4, and 3.8.0.
    # Not testing for 3.5.4.
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        pip install requirements.txt
      env: PATH=/c/Python36:/c/Python/36/Scripts:$PATH
      install:
        - python --version
    - name: "Python 3.7.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.5
        - python -m pip install --upgrade pip
        - pip install requirements.txt
      env: PATH=/c/Python37:/c/Python/37/Scripts:$PATH
      install:
        - python --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install requirements38.txt
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - python --version